# Generated by Django 5.2.8 on 2025-11-07 01:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_pac', models.CharField(max_length=100)),
                ('ape_pac', models.CharField(max_length=100)),
                ('edad_pac', models.PositiveIntegerField()),
                ('genero_pac', models.CharField(max_length=20)),
                ('tel_pac', models.CharField(max_length=15)),
                ('correo_pac', models.EmailField(max_length=80, unique=True)),
                ('direccion_pac', models.CharField(max_length=120)),
                ('fecha_reg_pac', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Terapeuta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_tep', models.CharField(max_length=100)),
                ('ape_tep', models.CharField(max_length=100)),
                ('especialidad_tep', models.CharField(choices=[('Física', 'Física'), ('Psicológica', 'Psicológica'), ('Ocupacional', 'Ocupacional'), ('Lenguaje', 'Lenguaje'), ('Otra', 'Otra')], max_length=100)),
                ('tel_tep', models.CharField(max_length=15)),
                ('correo_tep', models.EmailField(max_length=80, unique=True)),
                ('horario_tep', models.CharField(default='Lunes a Viernes', max_length=50)),
                ('experiencia_tep', models.PositiveIntegerField(help_text='Años de experiencia')),
            ],
        ),
        migrations.CreateModel(
            name='Terapia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_ter', models.CharField(max_length=100)),
                ('desc_ter', models.TextField(blank=True, null=True)),
                ('duracion_ter', models.PositiveIntegerField(help_text='Duración en minutos')),
                ('costo_ter', models.DecimalField(decimal_places=2, max_digits=8)),
                ('frecuencia_ter', models.CharField(max_length=50)),
                ('nivel_ter', models.CharField(choices=[('Física', 'Física'), ('Psicológica', 'Psicológica'), ('Ocupacional', 'Ocupacional'), ('Lenguaje', 'Lenguaje')], max_length=50)),
                ('fecha_inicio', models.DateField()),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terapias', to='app_paciente.paciente')),
                ('terapeutas', models.ManyToManyField(related_name='terapias', to='app_paciente.terapeuta')),
            ],
        ),
    ]
